job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-finland
    APP_HOSTPATH: finland
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GOOGLE_PROJECT_ID: planet-4-151612
    GCLOUD_CLUSTER: p4-development
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-finland
    NEWRELIC_APPNAME: P4 Finland Development
    WP_DB_NAME: planet4-finland_wordpress_develop
    WP_STATELESS_BUCKET: planet4-finland-stateless-develop
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: release.k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: finland
    HELM_RELEASE: planet4-finland-release
    NEWRELIC_APPNAME: P4 Finland Release
    WP_DB_NAME: planet4-finland_wordpress_release
    WP_STATELESS_BUCKET: planet4-finland-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: master.k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: finland
    HELM_RELEASE: planet4-finland-master
    MIN_REPLICA_COUNT: 2
    NEWRELIC_APPNAME: P4 Finland Production
    WP_DB_NAME: planet4-finland_wordpress_master
    WP_STATELESS_BUCKET: planet4-finland-stateless